version: 2
jobs:
  build:
    macos:
      xcode: "9.4.1" # macOS 10.13.3, the oldest version that CircleCI still supports
    steps:
      # Golang install

      # For some reason it is faster to curl into a file than to just
      # pipe the curl straight to tar.  Note that Go 1.15 requires
      # macOS 10.12 or newer.
      - run: curl https://dl.google.com/go/go1.15.5.darwin-amd64.tar.gz -o /tmp/go.tgz
      - run: sudo tar -C /usr/local -xzf /tmp/go.tgz

      # Golang paths
      - run:
          command: |
            echo 'export PATH=${PATH}:/usr/local/go/bin' >> ${BASH_ENV}


      - checkout
      - run: make test
