version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/go/src/github.com/datawire/pf
    steps:
      # Golang install

      # For some reason it is faster to curl into a file than to just
      # pipe the curl straight to tar.
      - run: curl https://dl.google.com/go/go1.10.2.darwin-amd64.tar.gz -o /tmp/go.tgz
      - run: sudo tar -C /usr/local -xzf /tmp/go.tgz

      # Golang paths
      - run:
          command: |
            echo 'export PATH=${PATH}:/usr/local/go/bin' >> ${BASH_ENV}


      - checkout
      - run: make test
